In [4]:
from nltk.cluster import KMeansClusterer
from nltk.cluster import euclidean_distance
from nltk.cluster.util import cosine_distance
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl
import seaborn as sb

In [26]:
x = np.array([[6,5,4,3],[6,5,4,3]])
print(x)

[[6 5 4 3]
 [6 5 4 3]]


In [27]:
trans = np.array(x.T)
trans

array([[6, 6],
       [5, 5],
       [4, 4],
       [3, 3]])

In [31]:
kmeans = KMeansClusterer(2, euclidean_distance, avoid_empty_clusters=True)
var = kmeans.cluster(trans, True)


In [32]:
new = np.array(kmeans.means())

In [33]:
new

array([[4.99999994, 4.99999994],
       [3.        , 3.        ]])

In [34]:
trans = np.array(new.T)
trans

array([[4.99999994, 3.        ],
       [4.99999994, 3.        ]])